name: format
on:
    pull_request:
        branches:
            - main
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: 'https://registry.npmjs.org'
            - name: Install dependencies
              run: npm ci
            - name: Run linter and formatter
              run: npm run clean
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Format code
                  branch: ${{ github.head_ref }}
